#!/usr/bin/env bash

echo '[WARNING] gscam_node is an interim dependency and will be removed in the next release! Please change all launchfiles back to use "gscam" instead of "gscam_node"'

/home/nlintz/Documents/Olin/2014-2015/Fall/CompRobo/comprobo2014/devel/lib/gscam/gscam
